### ISSUE TITLE
Python error in interactive user prompt during creation of new derivation

### ISSUE THREAD

**Issue by bhpayne** [allofphysicsgraph/proofofconcept#39]
selected declareInitialExpr
Latex expansion: latex here

existing derivation steps:
{'infrule': 'declareInitialExpr', 'input': [], 'infrule indx': 6545819, 'feed': [], 'output': [{'latex': 'W_{net out} = Q_{in} - Q_{out}', 'step indx output': 1872040, 'expr indx': 332248408}]}

number of input expressions: 0, number of feeds: 0, number of output expressions: 1

Choice for providing step content for output: 
1 provide new Latex
2 use existing expression index from above list
selection [1]: 

--> no selection from user; defaulting to 
1
output expression Latex,    1 of 1: \eta_{thermal} = W_{net out}/Q_{in}

Resulting dic:
{'infrule': 'declareInitialExpr', 'input': [], 'feed': [], 'output': [{'latex': '\\eta_{thermal} = W_{net out}/Q_{in}', 'expr indx': 432340984}]}
derivation name: thermal efficiency and work and heat
Traceback (most recent call last):
  File "bin/interactive_user_prompt.py", line 643, in <module>
    list_of_expr,connection_expr_temp,list_of_feeds,connection_infrule_temp,output_path)
  File "bin/interactive_user_prompt.py", line 164, in first_choice
    connection_expr_temp,list_of_feeds,connection_infrule_temp,output_path)
  File "bin/interactive_user_prompt.py", line 231, in start_new_derivation
    connection_infrule_temp,list_of_feeds,output_path)
  File "bin/interactive_user_prompt.py", line 345, in write_steps_to_file
    step_ary=assign_temp_indx(step_ary)
  File "bin/interactive_user_prompt.py", line 319, in assign_temp_indx
    temp_indx_for_this_expr_indx = expr_indx_exists_in_ary(expr_indx,step_indx,step_ary)
  File "bin/interactive_user_prompt.py", line 289, in expr_indx_exists_in_ary
    if ((step_ary[step_indx]['output'][input_indx]['expr indx'] == test_indx) and \
UnboundLocalError: local variable 'input_indx' referenced before assignment

**Comment by bhpayne** [comment]
I need to add more validation to functions rather than assuming that what I reference exists in the data structures.

**Comment by bhpayne** [comment]
git commit 95a6f37 fixed two bugs; I was referencing "input_*" in an output function
